### ISSUE TITLE
compact markdown friendly logs

### ISSUE THREAD

**Issue by A** [A/task-cli#3]
``` js
~/Projects/tasks/cli master ❯ tasks get

#0 fix 1 top pixel for banner
tags: #work


#1 figuring out with ampressandjs
tags:  #work


#3 figuring out with regions
tags:  #inbox

~/Projects/tasks/cli master ❯
```

going to:

``` js
~/Projects/tasks/cli master ❯ tasks get
# Tasks or tag
- [ ] #0 fix 1 top pixel for banner  
  tags: #work
- [ ] #1 figuring out with ampressandjs
  tags:  #work
- [x] #3 figuring out with regions
  tags:  #inbox
~/Projects/tasks/cli master ❯
```

 You have simply to share this tasks with gist like [here](https://gist.github.com/shuvalov-anton/8ffd87228e084f72763f)
